apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-provider-secret
type: Opaque
stringData:
  credentials: |
    {
      "token": "orchard-bootstrap-token-v0.Y3Jvc3NwbGFuZS1wcm92aWRlcg.YTdkM2U1ZGUtZjU3ZS00NmY3LTgxNmUtNWZjZmRmNDgzZDMz"
    }
---
apiVersion: orchard.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: default
spec:
  baseURL: "http://host.docker.internal:6120/v1"
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-secret
      key: credentials
---
apiVersion: orchard.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  baseURL: "http://host.docker.internal:6120/v1"
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-secret
      key: credentials
